@startuml

start

header fan control v0.2
title Алгоритм одного цикла


:считывание датчика освещенности;

if (освещение ниже порогового значения?) then (да)
	stop
endif 

:запустить таймер 1;
:дождаться конца таймера 1;

if (освещение все еще есть?) then (нет) 
	stop
endif

:начать вентилирование;

repeat

	repeat
	:считывание датчика освещенности;
	repeat while (освещение есть?) is (да)
	
	:запустить таймер 2;
	:дождаться конца таймера 2;

backward: сбросить таймер 2; 
repeat while (освещение есть?) is (да)

:прекратить вентилирование;



stop

@enduml